# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips_code', models.CharField(max_length=2, verbose_name='FIPS code')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('postal_code', models.CharField(max_length=2, verbose_name='USPS code')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
